services:
  airflow:
    build:
      context: ./
      dockerfile: Dockerfile.airflow
    image: airflowimage
    volumes:
      - ./:/app/
    container_name: xray-diagnosis-airflow
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 8g
          cpus: '4'
  
  flaskapp:
    build:
      context: ./
      dockerfile: Dockerfile.flask
    image: flaskimage
    volumes:
      - ./:/app/
    container_name: xray-diagnosis-flask
    ports:
      - "80:80"