stages:
  training:
    cmd: python src/pipeline/training_pipeline.py
    deps:
      - src/components/data_ingestion.py
      - src/components/model_trainer.py
      - src/components/model_tester.py

    outs:
      - data/ingested_data
      - artifacts/model.pkl